apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: jupyterhub
    team: opendatahub
  name: jupyterhub-metrics
spec:
  endpoints:
    - port: 8080-tcp
  selector:
    matchLabels:
      app: jupyterhub
