apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: opendatahub
  name: odhservicemonitor
spec:
  endpoints:
    - port: metrics # Argo
    - port: http-metrics # Open Data Hub Operator
    - port: cr-metrics # Open Data Hub Operator
    - bearerTokenSecret:
        key: PROMETHEUS_API_TOKEN
        name: jupyterhub
      port: 8080-tcp # Jupyterhub
      path: "/metrics"
  selector:
    matchLabels:
      opendatahub.io/component: "true"
