{
 "title": "Argo Workflow temp",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(argo_workflow_status_phase, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Argo Failed Workflows",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(argo_workflow_status_phase{namespace=~\"$Namespace\",phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Argo Succesful Workflows",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(argo_workflow_status_phase{namespace=~\"$Namespace\",phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Workflow Run Time",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "argo_workflow_completion_time{namespace=~\"$Namespace\"} - argo_workflow_start_time{namespace=~\"$Namespace\"}"
    }
   ]
  }
 ]
}