apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive
    hive: metastore
  name: hive-metastore
spec:
  ports:
    - name: meta
      port: 9083
      targetPort: meta
    - name: metrics
      port: 8082
  selector:
    app: hive
    hive: metastore
  sessionAffinity: None
