apiVersion: v1
kind: Secret
metadata:
  name: trino-db-secret
  labels:
    app: trino
  annotations:
    template.openshift.io/expose-username: "{.data['database-user']}"
    template.openshift.io/expose-password: "{.data['database-password']}"
stringData:
  database-user: "trino"
  database-password: "trino"
  database-name: "trino"
