---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
  config-worker.properties: |-
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://trino-service:8080
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  log.properties: |-
    io.trino=INFO
  node.properties: |-
    node.environment=$(trino_environment)
    node.data-dir=/tmp/data/trino
