apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels: {}
  name: nbviewer
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/odh-jupyterhub/nbviewer
    from:
      kind: DockerImage
      name: quay.io/odh-jupyterhub/nbviewer:latest
    name: latest
    referencePolicy:
      type: Source
