{
 "title": "Jupyterhub SLI/SLO",
 "tags": [ "SRE" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "user_id",
    "label": "User ID",
    "query": "kubelet_volume_stats_capacity_bytes"
   },
   {
    "name": "status_codes",
    "query": "label_values(jupyterhub_request_duration_seconds_count{job=\"jupyterhub\"},code)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_cpu_usage_seconds_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "JupyterHub SLI Dashboard",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# JupyterHub SLI Dashboard\n\nThis dashboard helps visualize the SLIs (Service Level Indicators) important for monitoring the JupyterHub service.\n\nThe main SLIs tracked are:\n* Availability \n* Latency\n* Saturation\n* Error"
   }
  },
  { "title": "SLI: Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": {
    "content": "![jupyterhubimage](https://avatars0.githubusercontent.com/u/17927519?s=200&v=4)"
   },
   "content": "![jupyterhubimage](https://avatars0.githubusercontent.com/u/17927519?s=200&v=4)"
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"jupyterhub\"}"
    },
    {}
   ]
  },
  {
   "title": "JupyterHub Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jupyterhub_running_servers", "legendFormat": "Running Servers" },
    { "expr": "jupyterhub_total_users", "legendFormat": "Total Users" }
   ]
  },
  { "title": "SLI: Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Init Server Spawn Duration",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 1, "y": 18 },
   "options": {
    "content": "The panel below displays the time taken for spawners to initialize and the histogram bucket distribution is visualized."
   }
  },
  {
   "title": "Hub Startup Duration",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 13, "y": 18 },
   "options": {
    "content": "The panel below displays the time taken for Hub to start and the histogram bucket distribution is visualized."
   }
  },
  {
   "title": "Init Server Spawn Duration",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jupyterhub_init_spawners_duration_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Hub Startup Duration",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 11, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jupyterhub_hub_startup_duration_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "SLI: Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pod CPU  Usage",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 2, "y": 36 },
   "options": {
    "content": "The panel below displays the CPU usage (%) for JupyterHub users over time."
   }
  },
  {
   "title": "Pod Memory Usage",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 36 },
   "options": {
    "content": "The panel below displays the memory usage (in `GiB`) for JupyterHub users over time."
   }
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{pod=~\"jupyterhub-nb.*\"}[5m])) by (pod))*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"jupyterhub-nb.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVC Storage Usage",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 53 },
   "options": {
    "content": "The panel below displays the PVC storage usage (%) for a specific JupyterHub user. To view the JupyterHub PVC storage for a user in the panel below, select the user id from `User ID` drop-down filter available on the top of this dashboard page."
   }
  },
  {
   "title": "PVC Storage Usage (%) for  $user_id",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{namespace=\"$namespace\",persistentvolumeclaim=~\"jupyterhub-nb-$user_id-pvc\", pod=\"prometheus-k8s-0\"})/(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\",persistentvolumeclaim=~\"jupyterhub-nb-$user_id-pvc\",pod=\"prometheus-k8s-0\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "SLI: Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "JupyterHub Server Spawn Fail Rate",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 1, "y": 73 },
   "options": {
    "content": "The panel below displays the server spawn fail rate for JupyterHub servers running. The fail rate is calculated over a duration of `5m`."
   }
  },
  {
   "title": "Hub Pod Restart Count",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 73 },
   "options": {
    "content": "The panel below displays the Hub pod restart count."
   }
  },
  {
   "title": "JupyterHub Server Spawn Fail Rate",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jupyterhub_server_spawn_duration_seconds_count{status=\"failure\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "Hub Pod Restart Count",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"jupyterhub-[0-9].*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOMKilled Pods",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 1, "y": 92 },
   "options": {
    "content": "The panel below displays the pods for JupyterHub which where `OOMKilled`"
   }
  },
  {
   "title": "HTTP Requests Error Codes",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 13, "y": 92 },
   "options": {
    "content": "The panel below displays the count of HTTP requests for various JupyterHub operations based on the HTTP status code. Select the HTTP status code from the `status_codes` drop-down filter available on top of this dashboard page to view the results."
   }
  },
  {
   "title": "OOMKilled Pods",
   "type": "graph",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kube_pod_container_status_terminated_reason{namespace=\"$namespace\", pod=~\"jupyterhub-nb-.*\", reason=\"OOMKilled\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request Error Codes",
   "type": "graph",
   "gridPos": { "h": 18, "w": 11, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jupyterhub_request_duration_seconds_count{code=~\"$status_codes\"}",
     "legendFormat": "{{code}},{{handler}}"
    },
    {}
   ]
  },
  {
   "title": "Container Creation Errors",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 1, "y": 113 },
   "options": {
    "content": "The panel below displays the pods/containers which encountered an error during container creation. The possible errors can be:\n* `ErrImagePull`\n* `ImagePullBackOff`\n* `CrashLoopBackoff`\n"
   }
  },
  {
   "title": "Container Creation Errors",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff\", pod=~\"jupyterhub-nb.*\", prometheus_replica=\"prometheus-k8s-0\"}"
    }
   ]
  }
 ]
}