{
 "title": "JupyterHub Usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "user_id",
    "label": "User ID",
    "query": "kubelet_volume_stats_capacity_bytes"
   },
   {
    "name": "namespace",
    "query": "label_values(container_cpu_usage_seconds_total, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "The panel below displays the PVC Usage (%) for all JupyterHub users."
   }
  },
  {
   "title": "JupyterHub PVC Storage",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 13, "y": 1 },
   "options": {
    "content": "\nTo view your Jupyter notebook storage details in the panel below, select your user id from the `User ID` drop-down filter \non the top left of this page.\n"
   }
  },
  {
   "title": "JupyterHub PVC Usage (%) per User",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\", pod=\"prometheus-k8s-0\"}/kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", pod=\"prometheus-k8s-0\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "JupyterHub PVC Storage for $user_id",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\".*$user_id.*\", pod=\"prometheus-k8s-0\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\".*$user_id.*\", pod=\"prometheus-k8s-0\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 14 },
   "options": {
    "content": "The panel below displays the CPU Usage (%) for all JupyterHub users.\nThe CPU usage is calculated for each container running in a pod."
   }
  },
  {
   "title": "Pod CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\", pod=~\"jupyterhub-nb.*\"}[5m])) by(pod,container))*100",
     "legendFormat": "{{container}} in {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Resources",
   "type": "text",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "options": {
    "content": "The panel below displays the following CPU resources for a specific JupyterHub pod:\n* CPU Requests\n* CPU Limits\n* CPU Usage (%)\n* CPU Throttling\n\nTo view the CPU details of a particular pod, select the user id from the `User ID` drop-down filter on the top left hand corner of this page."
   }
  },
  {
   "title": "CPU Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", prometheus_replica=\"prometheus-k8s-0\", pod=~\"jupyterhub-nb-$user_id\"}",
     "legendFormat": "pod cpu cores requests"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"$namespace\", pod=~\"jupyterhub-nb-$user_id\"}[5m])))*100",
     "legendFormat": "pod usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", prometheus_replica=\"prometheus-k8s-0\", pod=~\"jupyterhub-nb-$user_id\"}",
     "legendFormat": "pod cpu cores limits"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", namespace=\"$namespace\", pod=~\"jupyterhub-nb-$user_id\", prometheus_replica=\"prometheus-k8s-0\"}[5m])",
     "legendFormat": "pod throttle"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 41 },
   "options": {
    "content": "The panel below displays the Memory Usage (Bytes) for all JupyterHub users."
   }
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"$namespace\", pod=~\"jupyterhub-nb.*\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Resources",
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 50 },
   "options": {
    "content": "The panel below displays the following CPU resources for a specific JupyterHub pod:\n* Memory Usage\n* Memory Requests\n* Memory Limits\n\nTo view the Memory resources of a particular pod, select the user id from the `User ID` drop-down filter on the top left hand corner of this page."
   }
  },
  {
   "title": "Memory Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", prometheus_replica=\"prometheus-k8s-0\", pod=~\"jupyterhub-nb-$user_id\"}",
     "legendFormat": "pod memory requests"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=\"$namespace\", pod=~\"jupyterhub-nb-$user_id\"})",
     "legendFormat": "pod memory usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", prometheus_replica=\"prometheus-k8s-0\", pod=~\"jupyterhub-nb-$user_id\"}",
     "legendFormat": "pod memory limits"
    }
   ]
  }
 ]
}