apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ai-library/cluster
    name: ai-library-cluster
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: ai-library/operator
    # Note:  In order to utilize ai-library, you also need to have Seldon installed
    name: ai-library-operator
  - kustomizeConfig:
      parameters:
      # Note: The admin username is admin
      - name: SUPERSET_ADMIN_PASSWORD
        value: admin
      repoRef:
        name: manifests
        path: superset
    name: superset
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: openshift-operators
      repoRef:
        name: manifests
        path: kafka/cluster
    name: strimzi-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kafka/kafka
    name: kafka-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/cluster
    name: grafana-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/grafana
    name: grafana-instance
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/cluster
    name: radanalyticsio-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/operator
    name: radanalyticsio-spark-operator
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: prometheus/cluster
    name: prometheus-cluster
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: prometheus/operator
    name: prometheus-operator
  - kustomizeConfig:
      parameters:
        - name: s3_endpoint_url
          value: "s3.odh.com"
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      #- cuda
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: airflow/operator
    name: airflow-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: airflow/cluster
    name: airflow-cluster
  repos:
  - name: manifests
    uri: https://github.com/VedantMahabaleshwarkar/odh-manifests/tarball/dev
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v0.7-branch-openshift
  version: v0.7-branch-openshift
