apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub-mix
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  #Note: AI Library components requires seldon do be deployed first, make sure to place seldon before AIlibrary
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odhseldon/cluster
    name: odhseldon
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ai-library/cluster
    name: ai-library-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: ai-library/operator
    # Note:  In order to utilize ai-library, you also need to have Seldon installed
    name: ai-library-operator
  - kustomizeConfig:
      parameters:
      # Note: The admin username is admin
      - name: SUPERSET_ADMIN_PASSWORD
        value: admin
      repoRef:
        name: manifests
        path: superset
    name: superset
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: openshift-operators
      repoRef:
        name: manifests
        path: kafka/cluster
    name: strimzi-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kafka/kafka
    name: kafka-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/cluster
    name: grafana-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/grafana
    name: grafana-instance
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/cluster
    name: radanalyticsio-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/operator
    name: radanalyticsio-spark-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/cluster
    name: prometheus-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/operator
    name: prometheus-operator
  - kustomizeConfig:
      parameters:
        - name: s3_endpoint_url
          value: "s3.odh.com"
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      #- cuda
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: airflow/operator
    name: airflow-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: airflow/cluster
    name: airflow-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odhargo/cluster
    name: odhargo-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odhargo/odhargo
    name: odhargo
  - kustomizeConfig:
      repoRef:
        name: kf-manifests
        path: tf-training/tf-job-crds
    name: tf-job-crds
  - kustomizeConfig:
      repoRef:
        name: kf-manifests
        path: tf-training/tf-job-operator
    name: tf-job-operator
  - kustomizeConfig:
      repoRef:
        name: kf-manifests
        path: pytorch-job/pytorch-job-crds
    name: pytorch-job-crds
  - kustomizeConfig:
      repoRef:
        name: kf-manifests
        path: pytorch-job/pytorch-operator
    name: pytorch-operator
  repos:
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v1.0-branch-openshift  
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
  version: master
