kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: v1beta2-1.2.3-3.1.1
  name: spark-operator-webhook
spec:
  ports:
    - name: webhook
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/name: spark-operator

