apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-lab-elyra"
    opendatahub.io/notebook-image-name: "Elyra Notebook Image"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with Elyra-AI installed"
  name: s2i-lab-elyra
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: $(registry)/thoth-station/s2i-lab-elyra
    from:
      kind: DockerImage
      name: $(registry)/thoth-station/s2i-lab-elyra:v0.0.5
    name: "v0.0.5"
    referencePolicy:
      type: Source
