apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-minimal-notebook"
    opendatahub.io/notebook-image-name: "Minimal Notebook Image"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with minimal dependency set to start experimenting with Jupyter environment."
  name: s2i-minimal-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/thoth-station/s2i-minimal-notebook
    from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-minimal-notebook:v0.0.7
    name: "v0.0.7"
    referencePolicy:
      type: Source
