apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels: {}
  name: s2i-spark-scipy-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/odh-jupyterhub/s2i-spark-scipy-notebook
    from:
      kind: DockerImage
      name: quay.io/odh-jupyterhub/s2i-spark-scipy-notebook:3.6
    name: "3.6"
    referencePolicy:
      type: Source
