apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ceph
    daemon: nano
    name: ceph-nano
  name: ceph-nano
spec:
  replicas: 1
  serviceName: ceph-nano
  selector:
    matchLabels:
      app: ceph
  template:
    metadata:
      name: ceph-nano
      labels:
        app: ceph
        daemon: nano
    spec:
      serviceAccountName: ceph-nano
      containers:
      - image: ceph/daemon
        imagePullPolicy: Always
        name: ceph-nano
        ports:
        - containerPort: 8000
        name: cn-s3
        protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2G
          requests:
            cpu: "1"
            memory: 512M
        env:
        - name: NETWORK_AUTO_DETECT
          value: "4"
        - name: RGW_FRONTEND_PORT
          value: "8000"
          # Keep this for backward compatiblity, the option is gone since https://github.com/ceph/ceph-container/pull/1356
        - name: RGW_CIVETWEB_PORT
          value: "8000"
        - name: SREE_PORT
          value: "5001"
        - name: CEPH_DEMO_UID
          value: "nano"
          # Enable all of the ceph daemons to run
        - name: CEPH_DAEMON
          value: "demo"
        - name: DEBUG
          value: "verbose"
