---
apiVersion: v1
kind: Secret
metadata:
  name: hue-ini
type: Opaque
stringData:
  hue.ini: |
    # Full configuration:
    # https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini

    [desktop]
      # Hide unused apps
      app_blacklist=impala,security,jobbrowser,jobsub,pig,hbase,sqoop,zookeeper,spark,oozie,search
      secret_key=$(hue_secret_key)
      http_host=0.0.0.0
      http_port=8000
      time_zone=America/Los_Angeles
      django_debug_mode=false
      dev=false
      database_logging=false
      send_dbug_messages=false
      http_500_debug_mode=false
      enable_prometheus=true

      [[django_admins]]

      [[custom]]

      [[auth]]

      [[ldap]]
        [[[users]]]

        [[[groups]]]

        [[[ldap_servers]]]

      [[vcs]]

      [[database]]
        engine=mysql
        host=hue-mysql.$(namespace).svc
        port=3306
        user=$(database_user)
        password=$(database_password)
        name=$(database_name)

      [[session]]

      [[smtp]]
        host=localhost
        port=25
        user=
        password=
        tls=no

      [[knox]]

      [[kerberos]]

      [[oauth]]

      [[oidc]]

      [[metrics]]

      [[tracing]]

      [[task_server]]

      [[gc_accounts]]
        [[[default]]]

    [notebook]
      [[interpreters]]
        [[[hive]]]
          name=Hive
          interface=hiveserver2

        [[[impala]]]
          name=Impala
          interface=hiveserver2

        [[[sparksql]]]
          name=SparkSql
          interface=hiveserver2

        [[[text]]]
          name=Text
          interface=text

        [[[markdown]]]
          name=Markdown
          interface=text

    [dashboard]
      is_enabled=true
      has_sql_enabled=true
      has_report_enabled=true
      use_gridster=true
      has_widget_filter=false
      has_tree_widget=false

      [[engines]]
        [[[solr]]]
        analytics=true
        nesting=true

        [[[sql]]]
        analytics=true
        nesting=false

    [hadoop]
      [[hdfs_clusters]]
        [[[default]]]

      [[yarn_clusters]]
        [[[default]]]

    [beeswax]
      hive_server_host=thriftserver.$(namespace).svc
      hive_server_port=10000
      hive_conf_dir=/etc/hive/conf
      thrift_version=7

      [[ssl]]

    [metastore]
      enable_new_create_table=true
      force_hs2_metadata=false

    [impala]
      [[ssl]]

    [spark]

    [oozie]

    [filebrowser]

    [pig]

    [sqoop]

    [proxy]

    [hbase]

    [search]

    [libsolr]

    [indexer]

    [jobsub]

    [jobbrowser]

    [security]

    [zookeeper]
      [[clusters]]
        [[[default]]]

    [useradmin]
      [[password_policy]]

    [liboozie]
      oozie_url=

    [aws]
      [[aws_accounts]]
        [[[default]]]
          host=$(s3_endpoint_url)
          is_secure=$(s3_is_secure)
          calling_format=boto.s3.connection.OrdinaryCallingFormat
          access_key_id_script=/opt/hue/aws_access_key_id.sh
          secret_access_key_script=/opt/hue/aws_secret_access_key.sh

    [azure]
      [[azure_accounts]]
        [[[default]]]

      [[adls_clusters]]
        [[[default]]]

      [[abfs_clusters]]
        [[[default]]]

    [libsentry]

    [libzookeeper]

    [librdbms]
      [[databases]]

    [libsaml]

    [liboauth]

    [kafka]
      [[kafka]]

    [metadata]
      [[manager]]
      [[optimizer]]
      [[catalog]]
      [[navigator]]
      [[prometheus]]
