---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - target:
      kind: PersistentVolumeClaim
      version: v1
      name: trino-db-db
    path: pvc-patch.yaml
