apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appTypes: cuda-build-chain
    name: cuda
  spec:
    lookupPolicy:
      local: true
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appTypes: cuda-build-chain
    name: python-36-ubi7
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appName1: 10.1-base-ubi7
      appTypes: cuda-build-chain
    name: 10.1-base-ubi7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cuda:10.1-base-ubi7
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
    source:
      contextDir: 10.1/base
      git:
        ref: ubi7
        uri: https://github.com/harshad16/cuda.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        env:
        - name: S2I_IMAGE
          value: registry.access.redhat.com/ubi7/s2i-base
        from:
          kind: DockerImage
          name: registry.access.redhat.com/ubi7/s2i-base
        noCache: true
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appName1: 10.1-runtime-ubi7
      appTypes: cuda-build-chain
    name: 10.1-runtime-ubi7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cuda:10.1-runtime-ubi7
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
    source:
      contextDir: 10.1/runtime/
      git:
        ref: ubi7
        uri: https://github.com/harshad16/cuda.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: cuda:10.1-base-ubi7
        noCache: true
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appName1: 10.1-cudnn7-runtime-ubi7
      appTypes: cuda-build-chain
    name: 10.1-cudnn7-runtime-ubi7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cuda:10.1-cudnn7-runtime-ubi7
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
    source:
      contextDir: 10.1/runtime/cudnn7
      git:
        ref: ubi7
        uri: https://github.com/harshad16/cuda.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: cuda:10.1-runtime-ubi7
        noCache: true
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appName1: 10.1-devel-ubi7
      appTypes: cuda-build-chain
    name: 10.1-devel-ubi7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cuda:10.1-devel-ubi7
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
    source:
      contextDir: 10.1/devel/
      git:
        ref: ubi7
        uri: https://github.com/harshad16/cuda.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: cuda:10.1-runtime-ubi7
        noCache: true
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appName1: 10.1-cudnn7-devel-ubi7
      appTypes: cuda-build-chain
    name: 10.1-cudnn7-devel-ubi7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cuda:10.1-cudnn7-devel-ubi7
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
    source:
      contextDir: 10.1/devel/cudnn7
      git:
        ref: ubi7
        uri: https://github.com/harshad16/cuda.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: cuda:10.1-devel-ubi7
        noCache: true
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      appName: 10.1-cuda-chain-ubi7
      appName1: python-36-ubi7
      appTypes: cuda-build-chain
    name: python-36-ubi7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: python-36-ubi7:latest
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "4"
        memory: 4Gi
    source:
      contextDir: "3.6"
      git:
        ref: master
        uri: https://github.com/harshad16/s2i-python-container.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.rhel7
        from:
          kind: ImageStreamTag
          name: cuda:10.1-cudnn7-devel-ubi7
        noCache: true
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
kind: List
metadata: {}
