apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: s2i-minimal-notebook-gpu
    name: s2i-minimal-notebook-gpu
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: s2i-minimal-notebook-gpu
    name: s2i-minimal-notebook-gpu
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: s2i-minimal-notebook-gpu:3.6
    resources:
      limits:
        memory: 2Gi
    source:
      git:
        ref: master
        uri: 'https://github.com/thoth-station/s2i-minimal-notebook'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: $(cuda_version)-cuda-python-36-ubi7:latest
      type: Source
      env:
      - name: ENABLE_MICROPIPENV
        value: "1"
      - name: UPGRADE_PIP_TO_LATEST
        value: "1"
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: s2i-tensorflow-notebook-gpu
      opendatahub.io/notebook-image: "true"
    name: s2i-tensorflow-notebook-gpu
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: s2i-tensorflow-notebook-gpu
    name: s2i-tensorflow-notebook-gpu
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: s2i-tensorflow-notebook-gpu:3.6
    resources:
      limits:
        memory: 512Mi
    source:
      git:
        ref: master
        uri: 'https://github.com/thoth-station/s2i-tensorflow-notebook'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-minimal-notebook-gpu:3.6
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
