---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - spark-cluster.yaml

patchesJson6902:
  - path: thriftserver-config-patch.yaml
    target:
      kind: ConfigMap
      name: thriftserver-config
      version: v1

configurations:
  - params.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: thriftserver
  component.opendatahub.io/part-of: datacatalog

images:
  - name: spark-cluster-image
    newName: quay.io/opendatahub/spark-cluster-image
    newTag: 2.4.3-h2.7
