apiVersion: v1
kind: Secret
metadata:
  name: superset-config
  labels:
    app: superset
stringData:
  superset_config.py: |
      import os
      from flask_appbuilder.security.manager import AUTH_DB, AUTH_LDAP
      MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY', '')
      SQLALCHEMY_DATABASE_URI = 'postgresql://$(SUPERSET_DB_USERNAME):$(SUPERSET_DB_PASSWORD)@supersetdb:5432/supersetdb'
      SQLALCHEMY_TRACK_MODIFICATIONS = True
      SECRET_KEY = os.getenv('SUPERSET_SECRET_KEY','$(SUPERSET_SECRET_KEY)')
      DATA_DIR = '/var/lib/superset'
      LOG_LEVEL = '$(LOG_LEVEL)'
      FEATURE_FLAGS = {
        'ENABLE_TEMPLATE_PROCESSING': True,
      }
