apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- securitycontextconstraint.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: ceph-nano

configMapGenerator:
- name: ceph-nano-parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: ceph-nano-parameters
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace

configurations:
- params.yaml

