# permissions to do viewer airflowbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflowbase-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airflow.apache.org
  resources:
  - airflowbases/status
  verbs:
  - get
