apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jupyterhub
  label:
    app: jupyterhub
data:
  POSTGRESQL_USER: anVweXRlcmh1Yg== # "jupyterhub"
  POSTGRESQL_PASSWORD: c2VjcmV0cGFzc3dvcmQ= # "secretpassword"
  PROMETHEUS_API_TOKEN: ZjM3ODVlODczZGUxMjZlNTU0NGUzOWZkNzZkYWQwOGY1MmFmYTQ0MmYwOGZlNWIxODk2Njc0MTc3MDE5ODIzMQ # "openssl rand -hex 32"
  COOKIE_SECRET: ""
