apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-nodereader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:node-reader'
subjects:
- kind: ServiceAccount
  name: jupyterhub-hub
  namespace: $(namespace)
