apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels: {}
  name: jupyterhub-img
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: $(registry)/odh-jupyterhub/jupyterhub-img
    from:
      kind: DockerImage
      name: $(registry)/odh-jupyterhub/jupyterhub-img:v0.1.4
    name: latest
    referencePolicy:
      type: Source
