apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.first: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jupyterhub"}}'
    serviceaccounts.openshift.io/oauth-redirecturi.first: hub/oauth_callback
    serviceaccounts.openshift.io/oauth-want-challenges: 'false'
  labels:
    app: jupyterhub
  name: jupyterhub-hub
