varReference:
- path: roleRef/namespace
  kind: RoleBinding
  apiGroup: authorization.openshift.io
- path: data
  kind: ConfigMap
- path: metadata/annotations/volume.beta.kubernetes.io\/storage-class
  kind: PersistentVolumeClaim